// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { isSupabaseConfigured, supabase } from "../supabase/client";

let lovableAuth: ReturnType<typeof createLovableAuth> | undefined;

function getLovableAuth() {
  if (!lovableAuth) lovableAuth = createLovableAuth();
  return lovableAuth;
}

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      if (!isSupabaseConfigured()) {
        return { error: new Error("Supabase não configurado.") };
      }
      const result = await getLovableAuth().signInWithOAuth(provider, {
        ...opts,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
