/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AprenderRouteImport } from './routes/aprender'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutomotivaRouteImport } from './routes/automotiva'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CasosReaisRouteImport } from './routes/casos-reais'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CodigoDaComunidadeRouteImport } from './routes/codigo-da-comunidade'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as CuidadosRouteImport } from './routes/cuidados'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FluxoRouteImport } from './routes/fluxo'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as IaRouteImport } from './routes/ia'
import { Route as IdentificarRouteImport } from './routes/identificar'
import { Route as ParceriaRouteImport } from './routes/parceria'
import { Route as PhRouteImport } from './routes/ph'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SpaShellRouteImport } from './routes/spa-shell'
import { Route as TransicoesRouteImport } from './routes/transicoes'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as AuthenticatedModeracaoRouteImport } from './routes/_authenticated/moderacao'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as ComunidadeIndexRouteImport } from './routes/comunidade.index'
import { Route as ComunidadeNovoRouteImport } from './routes/comunidade.novo'
import { Route as ComunidadePerguntasRouteImport } from './routes/comunidade.perguntas'
import { Route as ComunidadeRankingRouteImport } from './routes/comunidade.ranking'
import { Route as EquipamentosIndexRouteImport } from './routes/equipamentos.index'
import { Route as EquipamentosSlugRouteImport } from './routes/equipamentos.$slug'
import { Route as EstofadosIndexRouteImport } from './routes/estofados.index'
import { Route as EstofadosSlugRouteImport } from './routes/estofados.$slug'
import { Route as FerramentasIndexRouteImport } from './routes/ferramentas.index'
import { Route as FerramentasDiluicaoRouteImport } from './routes/ferramentas.diluicao'
import { Route as FerramentasPrecificacaoRouteImport } from './routes/ferramentas.precificacao'
import { Route as FichasIndexRouteImport } from './routes/fichas.index'
import { Route as FichasSlugRouteImport } from './routes/fichas.$slug'
import { Route as GruposIndexRouteImport } from './routes/grupos.index'
import { Route as GruposSlugRouteImport } from './routes/grupos.$slug'
import { Route as ManchasIndexRouteImport } from './routes/manchas.index'
import { Route as ManchasSlugRouteImport } from './routes/manchas.$slug'
import { Route as OndeComprarIndexRouteImport } from './routes/onde-comprar.index'
import { Route as OndeComprarSlugRouteImport } from './routes/onde-comprar.$slug'
import { Route as OndeComprarCompararRouteImport } from './routes/onde-comprar.comparar'
import { Route as PHandleRouteImport } from './routes/p.$handle'
import { Route as PerguntasIndexRouteImport } from './routes/perguntas.index'
import { Route as PerguntasIdRouteImport } from './routes/perguntas.$id'
import { Route as PerguntasNovaRouteImport } from './routes/perguntas.nova'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as ProdutosCompararRouteImport } from './routes/produtos.comparar'
import { Route as TecidosIndexRouteImport } from './routes/tecidos.index'
import { Route as TecidosSlugRouteImport } from './routes/tecidos.$slug'
import { Route as ComunidadePostIdRouteImport } from './routes/comunidade.post.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderRoute = AprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomotivaRoute = AutomotivaRouteImport.update({
  id: '/automotiva',
  path: '/automotiva',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosReaisRoute = CasosReaisRouteImport.update({
  id: '/casos-reais',
  path: '/casos-reais',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigoDaComunidadeRoute = CodigoDaComunidadeRouteImport.update({
  id: '/codigo-da-comunidade',
  path: '/codigo-da-comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadosRoute = CuidadosRouteImport.update({
  id: '/cuidados',
  path: '/cuidados',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoRoute = FluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentificarRoute = IdentificarRouteImport.update({
  id: '/identificar',
  path: '/identificar',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceriaRoute = ParceriaRouteImport.update({
  id: '/parceria',
  path: '/parceria',
  getParentRoute: () => rootRouteImport,
} as any)
const PhRoute = PhRouteImport.update({
  id: '/ph',
  path: '/ph',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaShellRoute = SpaShellRouteImport.update({
  id: '/spa-shell',
  path: '/spa-shell',
  getParentRoute: () => rootRouteImport,
} as any)
const TransicoesRoute = TransicoesRouteImport.update({
  id: '/transicoes',
  path: '/transicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedModeracaoRoute = AuthenticatedModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ComunidadeIndexRoute = ComunidadeIndexRouteImport.update({
  id: '/comunidade/',
  path: '/comunidade/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeNovoRoute = ComunidadeNovoRouteImport.update({
  id: '/comunidade/novo',
  path: '/comunidade/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadePerguntasRoute = ComunidadePerguntasRouteImport.update({
  id: '/comunidade/perguntas',
  path: '/comunidade/perguntas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRankingRoute = ComunidadeRankingRouteImport.update({
  id: '/comunidade/ranking',
  path: '/comunidade/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosIndexRoute = EquipamentosIndexRouteImport.update({
  id: '/equipamentos/',
  path: '/equipamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosSlugRoute = EquipamentosSlugRouteImport.update({
  id: '/equipamentos/$slug',
  path: '/equipamentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EstofadosIndexRoute = EstofadosIndexRouteImport.update({
  id: '/estofados/',
  path: '/estofados/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstofadosSlugRoute = EstofadosSlugRouteImport.update({
  id: '/estofados/$slug',
  path: '/estofados/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasIndexRoute = FerramentasIndexRouteImport.update({
  id: '/ferramentas/',
  path: '/ferramentas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasDiluicaoRoute = FerramentasDiluicaoRouteImport.update({
  id: '/ferramentas/diluicao',
  path: '/ferramentas/diluicao',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasPrecificacaoRoute = FerramentasPrecificacaoRouteImport.update({
  id: '/ferramentas/precificacao',
  path: '/ferramentas/precificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasIndexRoute = FichasIndexRouteImport.update({
  id: '/fichas/',
  path: '/fichas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasSlugRoute = FichasSlugRouteImport.update({
  id: '/fichas/$slug',
  path: '/fichas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposIndexRoute = GruposIndexRouteImport.update({
  id: '/grupos/',
  path: '/grupos/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposSlugRoute = GruposSlugRouteImport.update({
  id: '/grupos/$slug',
  path: '/grupos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManchasIndexRoute = ManchasIndexRouteImport.update({
  id: '/manchas/',
  path: '/manchas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManchasSlugRoute = ManchasSlugRouteImport.update({
  id: '/manchas/$slug',
  path: '/manchas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComprarIndexRoute = OndeComprarIndexRouteImport.update({
  id: '/onde-comprar/',
  path: '/onde-comprar/',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComprarSlugRoute = OndeComprarSlugRouteImport.update({
  id: '/onde-comprar/$slug',
  path: '/onde-comprar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComprarCompararRoute = OndeComprarCompararRouteImport.update({
  id: '/onde-comprar/comparar',
  path: '/onde-comprar/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const PHandleRoute = PHandleRouteImport.update({
  id: '/p/$handle',
  path: '/p/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasIndexRoute = PerguntasIndexRouteImport.update({
  id: '/perguntas/',
  path: '/perguntas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasIdRoute = PerguntasIdRouteImport.update({
  id: '/perguntas/$id',
  path: '/perguntas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasNovaRoute = PerguntasNovaRouteImport.update({
  id: '/perguntas/nova',
  path: '/perguntas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosCompararRoute = ProdutosCompararRouteImport.update({
  id: '/produtos/comparar',
  path: '/produtos/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const TecidosIndexRoute = TecidosIndexRouteImport.update({
  id: '/tecidos/',
  path: '/tecidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TecidosSlugRoute = TecidosSlugRouteImport.update({
  id: '/tecidos/$slug',
  path: '/tecidos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadePostIdRoute = ComunidadePostIdRouteImport.update({
  id: '/comunidade/post/$id',
  path: '/comunidade/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/auth': typeof AuthRoute
  '/automotiva': typeof AutomotivaRoute
  '/buscar': typeof BuscarRoute
  '/casos-reais': typeof CasosReaisRoute
  '/checklist': typeof ChecklistRoute
  '/codigo-da-comunidade': typeof CodigoDaComunidadeRoute
  '/comecar': typeof ComecarRoute
  '/cuidados': typeof CuidadosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/favoritos': typeof FavoritosRoute
  '/fluxo': typeof FluxoRoute
  '/glossario': typeof GlossarioRoute
  '/guia': typeof GuiaRoute
  '/ia': typeof IaRoute
  '/identificar': typeof IdentificarRoute
  '/parceria': typeof ParceriaRoute
  '/ph': typeof PhRoute
  '/profissionais': typeof ProfissionaisRoute
  '/sobre': typeof SobreRoute
  '/spa-shell': typeof SpaShellRoute
  '/transicoes': typeof TransicoesRoute
  '/transparencia': typeof TransparenciaRoute
  '/moderacao': typeof AuthenticatedModeracaoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/comunidade/novo': typeof ComunidadeNovoRoute
  '/comunidade/perguntas': typeof ComunidadePerguntasRoute
  '/comunidade/ranking': typeof ComunidadeRankingRoute
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
  '/estofados/$slug': typeof EstofadosSlugRoute
  '/ferramentas/diluicao': typeof FerramentasDiluicaoRoute
  '/ferramentas/precificacao': typeof FerramentasPrecificacaoRoute
  '/fichas/$slug': typeof FichasSlugRoute
  '/grupos/$slug': typeof GruposSlugRoute
  '/manchas/$slug': typeof ManchasSlugRoute
  '/onde-comprar/$slug': typeof OndeComprarSlugRoute
  '/onde-comprar/comparar': typeof OndeComprarCompararRoute
  '/p/$handle': typeof PHandleRoute
  '/perguntas/$id': typeof PerguntasIdRoute
  '/perguntas/nova': typeof PerguntasNovaRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/comparar': typeof ProdutosCompararRoute
  '/tecidos/$slug': typeof TecidosSlugRoute
  '/comunidade/': typeof ComunidadeIndexRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
  '/estofados/': typeof EstofadosIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/fichas/': typeof FichasIndexRoute
  '/grupos/': typeof GruposIndexRoute
  '/manchas/': typeof ManchasIndexRoute
  '/onde-comprar/': typeof OndeComprarIndexRoute
  '/perguntas/': typeof PerguntasIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/tecidos/': typeof TecidosIndexRoute
  '/comunidade/post/$id': typeof ComunidadePostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/auth': typeof AuthRoute
  '/automotiva': typeof AutomotivaRoute
  '/buscar': typeof BuscarRoute
  '/casos-reais': typeof CasosReaisRoute
  '/checklist': typeof ChecklistRoute
  '/codigo-da-comunidade': typeof CodigoDaComunidadeRoute
  '/comecar': typeof ComecarRoute
  '/cuidados': typeof CuidadosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/favoritos': typeof FavoritosRoute
  '/fluxo': typeof FluxoRoute
  '/glossario': typeof GlossarioRoute
  '/guia': typeof GuiaRoute
  '/ia': typeof IaRoute
  '/identificar': typeof IdentificarRoute
  '/parceria': typeof ParceriaRoute
  '/ph': typeof PhRoute
  '/profissionais': typeof ProfissionaisRoute
  '/sobre': typeof SobreRoute
  '/spa-shell': typeof SpaShellRoute
  '/transicoes': typeof TransicoesRoute
  '/transparencia': typeof TransparenciaRoute
  '/moderacao': typeof AuthenticatedModeracaoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/comunidade/novo': typeof ComunidadeNovoRoute
  '/comunidade/perguntas': typeof ComunidadePerguntasRoute
  '/comunidade/ranking': typeof ComunidadeRankingRoute
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
  '/estofados/$slug': typeof EstofadosSlugRoute
  '/ferramentas/diluicao': typeof FerramentasDiluicaoRoute
  '/ferramentas/precificacao': typeof FerramentasPrecificacaoRoute
  '/fichas/$slug': typeof FichasSlugRoute
  '/grupos/$slug': typeof GruposSlugRoute
  '/manchas/$slug': typeof ManchasSlugRoute
  '/onde-comprar/$slug': typeof OndeComprarSlugRoute
  '/onde-comprar/comparar': typeof OndeComprarCompararRoute
  '/p/$handle': typeof PHandleRoute
  '/perguntas/$id': typeof PerguntasIdRoute
  '/perguntas/nova': typeof PerguntasNovaRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/comparar': typeof ProdutosCompararRoute
  '/tecidos/$slug': typeof TecidosSlugRoute
  '/comunidade': typeof ComunidadeIndexRoute
  '/equipamentos': typeof EquipamentosIndexRoute
  '/estofados': typeof EstofadosIndexRoute
  '/ferramentas': typeof FerramentasIndexRoute
  '/fichas': typeof FichasIndexRoute
  '/grupos': typeof GruposIndexRoute
  '/manchas': typeof ManchasIndexRoute
  '/onde-comprar': typeof OndeComprarIndexRoute
  '/perguntas': typeof PerguntasIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/tecidos': typeof TecidosIndexRoute
  '/comunidade/post/$id': typeof ComunidadePostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aprender': typeof AprenderRoute
  '/auth': typeof AuthRoute
  '/automotiva': typeof AutomotivaRoute
  '/buscar': typeof BuscarRoute
  '/casos-reais': typeof CasosReaisRoute
  '/checklist': typeof ChecklistRoute
  '/codigo-da-comunidade': typeof CodigoDaComunidadeRoute
  '/comecar': typeof ComecarRoute
  '/cuidados': typeof CuidadosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/favoritos': typeof FavoritosRoute
  '/fluxo': typeof FluxoRoute
  '/glossario': typeof GlossarioRoute
  '/guia': typeof GuiaRoute
  '/ia': typeof IaRoute
  '/identificar': typeof IdentificarRoute
  '/parceria': typeof ParceriaRoute
  '/ph': typeof PhRoute
  '/profissionais': typeof ProfissionaisRoute
  '/sobre': typeof SobreRoute
  '/spa-shell': typeof SpaShellRoute
  '/transicoes': typeof TransicoesRoute
  '/transparencia': typeof TransparenciaRoute
  '/_authenticated/moderacao': typeof AuthenticatedModeracaoRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/comunidade/novo': typeof ComunidadeNovoRoute
  '/comunidade/perguntas': typeof ComunidadePerguntasRoute
  '/comunidade/ranking': typeof ComunidadeRankingRoute
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
  '/estofados/$slug': typeof EstofadosSlugRoute
  '/ferramentas/diluicao': typeof FerramentasDiluicaoRoute
  '/ferramentas/precificacao': typeof FerramentasPrecificacaoRoute
  '/fichas/$slug': typeof FichasSlugRoute
  '/grupos/$slug': typeof GruposSlugRoute
  '/manchas/$slug': typeof ManchasSlugRoute
  '/onde-comprar/$slug': typeof OndeComprarSlugRoute
  '/onde-comprar/comparar': typeof OndeComprarCompararRoute
  '/p/$handle': typeof PHandleRoute
  '/perguntas/$id': typeof PerguntasIdRoute
  '/perguntas/nova': typeof PerguntasNovaRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/comparar': typeof ProdutosCompararRoute
  '/tecidos/$slug': typeof TecidosSlugRoute
  '/comunidade/': typeof ComunidadeIndexRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
  '/estofados/': typeof EstofadosIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/fichas/': typeof FichasIndexRoute
  '/grupos/': typeof GruposIndexRoute
  '/manchas/': typeof ManchasIndexRoute
  '/onde-comprar/': typeof OndeComprarIndexRoute
  '/perguntas/': typeof PerguntasIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/tecidos/': typeof TecidosIndexRoute
  '/comunidade/post/$id': typeof ComunidadePostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprender'
    | '/auth'
    | '/automotiva'
    | '/buscar'
    | '/casos-reais'
    | '/checklist'
    | '/codigo-da-comunidade'
    | '/comecar'
    | '/cuidados'
    | '/diagnostico'
    | '/favoritos'
    | '/fluxo'
    | '/glossario'
    | '/guia'
    | '/ia'
    | '/identificar'
    | '/parceria'
    | '/ph'
    | '/profissionais'
    | '/sobre'
    | '/spa-shell'
    | '/transicoes'
    | '/transparencia'
    | '/moderacao'
    | '/notificacoes'
    | '/painel'
    | '/perfil'
    | '/comunidade/novo'
    | '/comunidade/perguntas'
    | '/comunidade/ranking'
    | '/equipamentos/$slug'
    | '/estofados/$slug'
    | '/ferramentas/diluicao'
    | '/ferramentas/precificacao'
    | '/fichas/$slug'
    | '/grupos/$slug'
    | '/manchas/$slug'
    | '/onde-comprar/$slug'
    | '/onde-comprar/comparar'
    | '/p/$handle'
    | '/perguntas/$id'
    | '/perguntas/nova'
    | '/produtos/$slug'
    | '/produtos/comparar'
    | '/tecidos/$slug'
    | '/comunidade/'
    | '/equipamentos/'
    | '/estofados/'
    | '/ferramentas/'
    | '/fichas/'
    | '/grupos/'
    | '/manchas/'
    | '/onde-comprar/'
    | '/perguntas/'
    | '/produtos/'
    | '/tecidos/'
    | '/comunidade/post/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprender'
    | '/auth'
    | '/automotiva'
    | '/buscar'
    | '/casos-reais'
    | '/checklist'
    | '/codigo-da-comunidade'
    | '/comecar'
    | '/cuidados'
    | '/diagnostico'
    | '/favoritos'
    | '/fluxo'
    | '/glossario'
    | '/guia'
    | '/ia'
    | '/identificar'
    | '/parceria'
    | '/ph'
    | '/profissionais'
    | '/sobre'
    | '/spa-shell'
    | '/transicoes'
    | '/transparencia'
    | '/moderacao'
    | '/notificacoes'
    | '/painel'
    | '/perfil'
    | '/comunidade/novo'
    | '/comunidade/perguntas'
    | '/comunidade/ranking'
    | '/equipamentos/$slug'
    | '/estofados/$slug'
    | '/ferramentas/diluicao'
    | '/ferramentas/precificacao'
    | '/fichas/$slug'
    | '/grupos/$slug'
    | '/manchas/$slug'
    | '/onde-comprar/$slug'
    | '/onde-comprar/comparar'
    | '/p/$handle'
    | '/perguntas/$id'
    | '/perguntas/nova'
    | '/produtos/$slug'
    | '/produtos/comparar'
    | '/tecidos/$slug'
    | '/comunidade'
    | '/equipamentos'
    | '/estofados'
    | '/ferramentas'
    | '/fichas'
    | '/grupos'
    | '/manchas'
    | '/onde-comprar'
    | '/perguntas'
    | '/produtos'
    | '/tecidos'
    | '/comunidade/post/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aprender'
    | '/auth'
    | '/automotiva'
    | '/buscar'
    | '/casos-reais'
    | '/checklist'
    | '/codigo-da-comunidade'
    | '/comecar'
    | '/cuidados'
    | '/diagnostico'
    | '/favoritos'
    | '/fluxo'
    | '/glossario'
    | '/guia'
    | '/ia'
    | '/identificar'
    | '/parceria'
    | '/ph'
    | '/profissionais'
    | '/sobre'
    | '/spa-shell'
    | '/transicoes'
    | '/transparencia'
    | '/_authenticated/moderacao'
    | '/_authenticated/notificacoes'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/comunidade/novo'
    | '/comunidade/perguntas'
    | '/comunidade/ranking'
    | '/equipamentos/$slug'
    | '/estofados/$slug'
    | '/ferramentas/diluicao'
    | '/ferramentas/precificacao'
    | '/fichas/$slug'
    | '/grupos/$slug'
    | '/manchas/$slug'
    | '/onde-comprar/$slug'
    | '/onde-comprar/comparar'
    | '/p/$handle'
    | '/perguntas/$id'
    | '/perguntas/nova'
    | '/produtos/$slug'
    | '/produtos/comparar'
    | '/tecidos/$slug'
    | '/comunidade/'
    | '/equipamentos/'
    | '/estofados/'
    | '/ferramentas/'
    | '/fichas/'
    | '/grupos/'
    | '/manchas/'
    | '/onde-comprar/'
    | '/perguntas/'
    | '/produtos/'
    | '/tecidos/'
    | '/comunidade/post/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AprenderRoute: typeof AprenderRoute
  AuthRoute: typeof AuthRoute
  AutomotivaRoute: typeof AutomotivaRoute
  BuscarRoute: typeof BuscarRoute
  CasosReaisRoute: typeof CasosReaisRoute
  ChecklistRoute: typeof ChecklistRoute
  CodigoDaComunidadeRoute: typeof CodigoDaComunidadeRoute
  ComecarRoute: typeof ComecarRoute
  CuidadosRoute: typeof CuidadosRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  FavoritosRoute: typeof FavoritosRoute
  FluxoRoute: typeof FluxoRoute
  GlossarioRoute: typeof GlossarioRoute
  GuiaRoute: typeof GuiaRoute
  IaRoute: typeof IaRoute
  IdentificarRoute: typeof IdentificarRoute
  ParceriaRoute: typeof ParceriaRoute
  PhRoute: typeof PhRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  SobreRoute: typeof SobreRoute
  SpaShellRoute: typeof SpaShellRoute
  TransicoesRoute: typeof TransicoesRoute
  TransparenciaRoute: typeof TransparenciaRoute
  ComunidadeNovoRoute: typeof ComunidadeNovoRoute
  ComunidadePerguntasRoute: typeof ComunidadePerguntasRoute
  ComunidadeRankingRoute: typeof ComunidadeRankingRoute
  EquipamentosSlugRoute: typeof EquipamentosSlugRoute
  EstofadosSlugRoute: typeof EstofadosSlugRoute
  FerramentasDiluicaoRoute: typeof FerramentasDiluicaoRoute
  FerramentasPrecificacaoRoute: typeof FerramentasPrecificacaoRoute
  FichasSlugRoute: typeof FichasSlugRoute
  GruposSlugRoute: typeof GruposSlugRoute
  ManchasSlugRoute: typeof ManchasSlugRoute
  OndeComprarSlugRoute: typeof OndeComprarSlugRoute
  OndeComprarCompararRoute: typeof OndeComprarCompararRoute
  PHandleRoute: typeof PHandleRoute
  PerguntasIdRoute: typeof PerguntasIdRoute
  PerguntasNovaRoute: typeof PerguntasNovaRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosCompararRoute: typeof ProdutosCompararRoute
  TecidosSlugRoute: typeof TecidosSlugRoute
  ComunidadeIndexRoute: typeof ComunidadeIndexRoute
  EquipamentosIndexRoute: typeof EquipamentosIndexRoute
  EstofadosIndexRoute: typeof EstofadosIndexRoute
  FerramentasIndexRoute: typeof FerramentasIndexRoute
  FichasIndexRoute: typeof FichasIndexRoute
  GruposIndexRoute: typeof GruposIndexRoute
  ManchasIndexRoute: typeof ManchasIndexRoute
  OndeComprarIndexRoute: typeof OndeComprarIndexRoute
  PerguntasIndexRoute: typeof PerguntasIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
  TecidosIndexRoute: typeof TecidosIndexRoute
  ComunidadePostIdRoute: typeof ComunidadePostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender': {
      id: '/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AprenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automotiva': {
      id: '/automotiva'
      path: '/automotiva'
      fullPath: '/automotiva'
      preLoaderRoute: typeof AutomotivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos-reais': {
      id: '/casos-reais'
      path: '/casos-reais'
      fullPath: '/casos-reais'
      preLoaderRoute: typeof CasosReaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigo-da-comunidade': {
      id: '/codigo-da-comunidade'
      path: '/codigo-da-comunidade'
      fullPath: '/codigo-da-comunidade'
      preLoaderRoute: typeof CodigoDaComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidados': {
      id: '/cuidados'
      path: '/cuidados'
      fullPath: '/cuidados'
      preLoaderRoute: typeof CuidadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo': {
      id: '/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof FluxoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identificar': {
      id: '/identificar'
      path: '/identificar'
      fullPath: '/identificar'
      preLoaderRoute: typeof IdentificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceria': {
      id: '/parceria'
      path: '/parceria'
      fullPath: '/parceria'
      preLoaderRoute: typeof ParceriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ph': {
      id: '/ph'
      path: '/ph'
      fullPath: '/ph'
      preLoaderRoute: typeof PhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa-shell': {
      id: '/spa-shell'
      path: '/spa-shell'
      fullPath: '/spa-shell'
      preLoaderRoute: typeof SpaShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transicoes': {
      id: '/transicoes'
      path: '/transicoes'
      fullPath: '/transicoes'
      preLoaderRoute: typeof TransicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/moderacao': {
      id: '/_authenticated/moderacao'
      path: '/moderacao'
      fullPath: '/moderacao'
      preLoaderRoute: typeof AuthenticatedModeracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/comunidade/': {
      id: '/comunidade/'
      path: '/comunidade'
      fullPath: '/comunidade/'
      preLoaderRoute: typeof ComunidadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade/novo': {
      id: '/comunidade/novo'
      path: '/comunidade/novo'
      fullPath: '/comunidade/novo'
      preLoaderRoute: typeof ComunidadeNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade/perguntas': {
      id: '/comunidade/perguntas'
      path: '/comunidade/perguntas'
      fullPath: '/comunidade/perguntas'
      preLoaderRoute: typeof ComunidadePerguntasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade/ranking': {
      id: '/comunidade/ranking'
      path: '/comunidade/ranking'
      fullPath: '/comunidade/ranking'
      preLoaderRoute: typeof ComunidadeRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/': {
      id: '/equipamentos/'
      path: '/equipamentos'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof EquipamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/$slug': {
      id: '/equipamentos/$slug'
      path: '/equipamentos/$slug'
      fullPath: '/equipamentos/$slug'
      preLoaderRoute: typeof EquipamentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estofados/': {
      id: '/estofados/'
      path: '/estofados'
      fullPath: '/estofados/'
      preLoaderRoute: typeof EstofadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estofados/$slug': {
      id: '/estofados/$slug'
      path: '/estofados/$slug'
      fullPath: '/estofados/$slug'
      preLoaderRoute: typeof EstofadosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/': {
      id: '/ferramentas/'
      path: '/ferramentas'
      fullPath: '/ferramentas/'
      preLoaderRoute: typeof FerramentasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/diluicao': {
      id: '/ferramentas/diluicao'
      path: '/ferramentas/diluicao'
      fullPath: '/ferramentas/diluicao'
      preLoaderRoute: typeof FerramentasDiluicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/precificacao': {
      id: '/ferramentas/precificacao'
      path: '/ferramentas/precificacao'
      fullPath: '/ferramentas/precificacao'
      preLoaderRoute: typeof FerramentasPrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas/': {
      id: '/fichas/'
      path: '/fichas'
      fullPath: '/fichas/'
      preLoaderRoute: typeof FichasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas/$slug': {
      id: '/fichas/$slug'
      path: '/fichas/$slug'
      fullPath: '/fichas/$slug'
      preLoaderRoute: typeof FichasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/': {
      id: '/grupos/'
      path: '/grupos'
      fullPath: '/grupos/'
      preLoaderRoute: typeof GruposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/$slug': {
      id: '/grupos/$slug'
      path: '/grupos/$slug'
      fullPath: '/grupos/$slug'
      preLoaderRoute: typeof GruposSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manchas/': {
      id: '/manchas/'
      path: '/manchas'
      fullPath: '/manchas/'
      preLoaderRoute: typeof ManchasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manchas/$slug': {
      id: '/manchas/$slug'
      path: '/manchas/$slug'
      fullPath: '/manchas/$slug'
      preLoaderRoute: typeof ManchasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comprar/': {
      id: '/onde-comprar/'
      path: '/onde-comprar'
      fullPath: '/onde-comprar/'
      preLoaderRoute: typeof OndeComprarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comprar/$slug': {
      id: '/onde-comprar/$slug'
      path: '/onde-comprar/$slug'
      fullPath: '/onde-comprar/$slug'
      preLoaderRoute: typeof OndeComprarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comprar/comparar': {
      id: '/onde-comprar/comparar'
      path: '/onde-comprar/comparar'
      fullPath: '/onde-comprar/comparar'
      preLoaderRoute: typeof OndeComprarCompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$handle': {
      id: '/p/$handle'
      path: '/p/$handle'
      fullPath: '/p/$handle'
      preLoaderRoute: typeof PHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas/': {
      id: '/perguntas/'
      path: '/perguntas'
      fullPath: '/perguntas/'
      preLoaderRoute: typeof PerguntasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas/$id': {
      id: '/perguntas/$id'
      path: '/perguntas/$id'
      fullPath: '/perguntas/$id'
      preLoaderRoute: typeof PerguntasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas/nova': {
      id: '/perguntas/nova'
      path: '/perguntas/nova'
      fullPath: '/perguntas/nova'
      preLoaderRoute: typeof PerguntasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/comparar': {
      id: '/produtos/comparar'
      path: '/produtos/comparar'
      fullPath: '/produtos/comparar'
      preLoaderRoute: typeof ProdutosCompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecidos/': {
      id: '/tecidos/'
      path: '/tecidos'
      fullPath: '/tecidos/'
      preLoaderRoute: typeof TecidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecidos/$slug': {
      id: '/tecidos/$slug'
      path: '/tecidos/$slug'
      fullPath: '/tecidos/$slug'
      preLoaderRoute: typeof TecidosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade/post/$id': {
      id: '/comunidade/post/$id'
      path: '/comunidade/post/$id'
      fullPath: '/comunidade/post/$id'
      preLoaderRoute: typeof ComunidadePostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedModeracaoRoute: typeof AuthenticatedModeracaoRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedModeracaoRoute: AuthenticatedModeracaoRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AprenderRoute: AprenderRoute,
  AuthRoute: AuthRoute,
  AutomotivaRoute: AutomotivaRoute,
  BuscarRoute: BuscarRoute,
  CasosReaisRoute: CasosReaisRoute,
  ChecklistRoute: ChecklistRoute,
  CodigoDaComunidadeRoute: CodigoDaComunidadeRoute,
  ComecarRoute: ComecarRoute,
  CuidadosRoute: CuidadosRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  FavoritosRoute: FavoritosRoute,
  FluxoRoute: FluxoRoute,
  GlossarioRoute: GlossarioRoute,
  GuiaRoute: GuiaRoute,
  IaRoute: IaRoute,
  IdentificarRoute: IdentificarRoute,
  ParceriaRoute: ParceriaRoute,
  PhRoute: PhRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  SobreRoute: SobreRoute,
  SpaShellRoute: SpaShellRoute,
  TransicoesRoute: TransicoesRoute,
  TransparenciaRoute: TransparenciaRoute,
  ComunidadeNovoRoute: ComunidadeNovoRoute,
  ComunidadePerguntasRoute: ComunidadePerguntasRoute,
  ComunidadeRankingRoute: ComunidadeRankingRoute,
  EquipamentosSlugRoute: EquipamentosSlugRoute,
  EstofadosSlugRoute: EstofadosSlugRoute,
  FerramentasDiluicaoRoute: FerramentasDiluicaoRoute,
  FerramentasPrecificacaoRoute: FerramentasPrecificacaoRoute,
  FichasSlugRoute: FichasSlugRoute,
  GruposSlugRoute: GruposSlugRoute,
  ManchasSlugRoute: ManchasSlugRoute,
  OndeComprarSlugRoute: OndeComprarSlugRoute,
  OndeComprarCompararRoute: OndeComprarCompararRoute,
  PHandleRoute: PHandleRoute,
  PerguntasIdRoute: PerguntasIdRoute,
  PerguntasNovaRoute: PerguntasNovaRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosCompararRoute: ProdutosCompararRoute,
  TecidosSlugRoute: TecidosSlugRoute,
  ComunidadeIndexRoute: ComunidadeIndexRoute,
  EquipamentosIndexRoute: EquipamentosIndexRoute,
  EstofadosIndexRoute: EstofadosIndexRoute,
  FerramentasIndexRoute: FerramentasIndexRoute,
  FichasIndexRoute: FichasIndexRoute,
  GruposIndexRoute: GruposIndexRoute,
  ManchasIndexRoute: ManchasIndexRoute,
  OndeComprarIndexRoute: OndeComprarIndexRoute,
  PerguntasIndexRoute: PerguntasIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
  TecidosIndexRoute: TecidosIndexRoute,
  ComunidadePostIdRoute: ComunidadePostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
