/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AprenderRouteImport } from './routes/aprender'
import { Route as AutomotivaRouteImport } from './routes/automotiva'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as CuidadosRouteImport } from './routes/cuidados'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FluxoRouteImport } from './routes/fluxo'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as IdentificarRouteImport } from './routes/identificar'
import { Route as ParceriaRouteImport } from './routes/parceria'
import { Route as PhRouteImport } from './routes/ph'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as EquipamentosIndexRouteImport } from './routes/equipamentos.index'
import { Route as EquipamentosSlugRouteImport } from './routes/equipamentos.$slug'
import { Route as EstofadosIndexRouteImport } from './routes/estofados.index'
import { Route as EstofadosSlugRouteImport } from './routes/estofados.$slug'
import { Route as FerramentasIndexRouteImport } from './routes/ferramentas.index'
import { Route as FerramentasDiluicaoRouteImport } from './routes/ferramentas.diluicao'
import { Route as FerramentasPrecificacaoRouteImport } from './routes/ferramentas.precificacao'
import { Route as FichasIndexRouteImport } from './routes/fichas.index'
import { Route as FichasSlugRouteImport } from './routes/fichas.$slug'
import { Route as ManchasIndexRouteImport } from './routes/manchas.index'
import { Route as ManchasSlugRouteImport } from './routes/manchas.$slug'
import { Route as OndeComprarIndexRouteImport } from './routes/onde-comprar.index'
import { Route as OndeComprarSlugRouteImport } from './routes/onde-comprar.$slug'
import { Route as OndeComprarCompararRouteImport } from './routes/onde-comprar.comparar'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as ProdutosCompararRouteImport } from './routes/produtos.comparar'
import { Route as TecidosIndexRouteImport } from './routes/tecidos.index'
import { Route as TecidosSlugRouteImport } from './routes/tecidos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderRoute = AprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomotivaRoute = AutomotivaRouteImport.update({
  id: '/automotiva',
  path: '/automotiva',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadosRoute = CuidadosRouteImport.update({
  id: '/cuidados',
  path: '/cuidados',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoRoute = FluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentificarRoute = IdentificarRouteImport.update({
  id: '/identificar',
  path: '/identificar',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceriaRoute = ParceriaRouteImport.update({
  id: '/parceria',
  path: '/parceria',
  getParentRoute: () => rootRouteImport,
} as any)
const PhRoute = PhRouteImport.update({
  id: '/ph',
  path: '/ph',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosIndexRoute = EquipamentosIndexRouteImport.update({
  id: '/equipamentos/',
  path: '/equipamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosSlugRoute = EquipamentosSlugRouteImport.update({
  id: '/equipamentos/$slug',
  path: '/equipamentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EstofadosIndexRoute = EstofadosIndexRouteImport.update({
  id: '/estofados/',
  path: '/estofados/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstofadosSlugRoute = EstofadosSlugRouteImport.update({
  id: '/estofados/$slug',
  path: '/estofados/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasIndexRoute = FerramentasIndexRouteImport.update({
  id: '/ferramentas/',
  path: '/ferramentas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasDiluicaoRoute = FerramentasDiluicaoRouteImport.update({
  id: '/ferramentas/diluicao',
  path: '/ferramentas/diluicao',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasPrecificacaoRoute = FerramentasPrecificacaoRouteImport.update({
  id: '/ferramentas/precificacao',
  path: '/ferramentas/precificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasIndexRoute = FichasIndexRouteImport.update({
  id: '/fichas/',
  path: '/fichas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasSlugRoute = FichasSlugRouteImport.update({
  id: '/fichas/$slug',
  path: '/fichas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManchasIndexRoute = ManchasIndexRouteImport.update({
  id: '/manchas/',
  path: '/manchas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManchasSlugRoute = ManchasSlugRouteImport.update({
  id: '/manchas/$slug',
  path: '/manchas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComprarIndexRoute = OndeComprarIndexRouteImport.update({
  id: '/onde-comprar/',
  path: '/onde-comprar/',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComprarSlugRoute = OndeComprarSlugRouteImport.update({
  id: '/onde-comprar/$slug',
  path: '/onde-comprar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComprarCompararRoute = OndeComprarCompararRouteImport.update({
  id: '/onde-comprar/comparar',
  path: '/onde-comprar/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosCompararRoute = ProdutosCompararRouteImport.update({
  id: '/produtos/comparar',
  path: '/produtos/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const TecidosIndexRoute = TecidosIndexRouteImport.update({
  id: '/tecidos/',
  path: '/tecidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TecidosSlugRoute = TecidosSlugRouteImport.update({
  id: '/tecidos/$slug',
  path: '/tecidos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/automotiva': typeof AutomotivaRoute
  '/buscar': typeof BuscarRoute
  '/checklist': typeof ChecklistRoute
  '/comecar': typeof ComecarRoute
  '/comunidade': typeof ComunidadeRoute
  '/cuidados': typeof CuidadosRoute
  '/favoritos': typeof FavoritosRoute
  '/fluxo': typeof FluxoRoute
  '/glossario': typeof GlossarioRoute
  '/guia': typeof GuiaRoute
  '/identificar': typeof IdentificarRoute
  '/parceria': typeof ParceriaRoute
  '/ph': typeof PhRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
  '/estofados/$slug': typeof EstofadosSlugRoute
  '/ferramentas/diluicao': typeof FerramentasDiluicaoRoute
  '/ferramentas/precificacao': typeof FerramentasPrecificacaoRoute
  '/fichas/$slug': typeof FichasSlugRoute
  '/manchas/$slug': typeof ManchasSlugRoute
  '/onde-comprar/$slug': typeof OndeComprarSlugRoute
  '/onde-comprar/comparar': typeof OndeComprarCompararRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/comparar': typeof ProdutosCompararRoute
  '/tecidos/$slug': typeof TecidosSlugRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
  '/estofados/': typeof EstofadosIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/fichas/': typeof FichasIndexRoute
  '/manchas/': typeof ManchasIndexRoute
  '/onde-comprar/': typeof OndeComprarIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/tecidos/': typeof TecidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/automotiva': typeof AutomotivaRoute
  '/buscar': typeof BuscarRoute
  '/checklist': typeof ChecklistRoute
  '/comecar': typeof ComecarRoute
  '/comunidade': typeof ComunidadeRoute
  '/cuidados': typeof CuidadosRoute
  '/favoritos': typeof FavoritosRoute
  '/fluxo': typeof FluxoRoute
  '/glossario': typeof GlossarioRoute
  '/guia': typeof GuiaRoute
  '/identificar': typeof IdentificarRoute
  '/parceria': typeof ParceriaRoute
  '/ph': typeof PhRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
  '/estofados/$slug': typeof EstofadosSlugRoute
  '/ferramentas/diluicao': typeof FerramentasDiluicaoRoute
  '/ferramentas/precificacao': typeof FerramentasPrecificacaoRoute
  '/fichas/$slug': typeof FichasSlugRoute
  '/manchas/$slug': typeof ManchasSlugRoute
  '/onde-comprar/$slug': typeof OndeComprarSlugRoute
  '/onde-comprar/comparar': typeof OndeComprarCompararRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/comparar': typeof ProdutosCompararRoute
  '/tecidos/$slug': typeof TecidosSlugRoute
  '/equipamentos': typeof EquipamentosIndexRoute
  '/estofados': typeof EstofadosIndexRoute
  '/ferramentas': typeof FerramentasIndexRoute
  '/fichas': typeof FichasIndexRoute
  '/manchas': typeof ManchasIndexRoute
  '/onde-comprar': typeof OndeComprarIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/tecidos': typeof TecidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/automotiva': typeof AutomotivaRoute
  '/buscar': typeof BuscarRoute
  '/checklist': typeof ChecklistRoute
  '/comecar': typeof ComecarRoute
  '/comunidade': typeof ComunidadeRoute
  '/cuidados': typeof CuidadosRoute
  '/favoritos': typeof FavoritosRoute
  '/fluxo': typeof FluxoRoute
  '/glossario': typeof GlossarioRoute
  '/guia': typeof GuiaRoute
  '/identificar': typeof IdentificarRoute
  '/parceria': typeof ParceriaRoute
  '/ph': typeof PhRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
  '/estofados/$slug': typeof EstofadosSlugRoute
  '/ferramentas/diluicao': typeof FerramentasDiluicaoRoute
  '/ferramentas/precificacao': typeof FerramentasPrecificacaoRoute
  '/fichas/$slug': typeof FichasSlugRoute
  '/manchas/$slug': typeof ManchasSlugRoute
  '/onde-comprar/$slug': typeof OndeComprarSlugRoute
  '/onde-comprar/comparar': typeof OndeComprarCompararRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/comparar': typeof ProdutosCompararRoute
  '/tecidos/$slug': typeof TecidosSlugRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
  '/estofados/': typeof EstofadosIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/fichas/': typeof FichasIndexRoute
  '/manchas/': typeof ManchasIndexRoute
  '/onde-comprar/': typeof OndeComprarIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/tecidos/': typeof TecidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprender'
    | '/automotiva'
    | '/buscar'
    | '/checklist'
    | '/comecar'
    | '/comunidade'
    | '/cuidados'
    | '/favoritos'
    | '/fluxo'
    | '/glossario'
    | '/guia'
    | '/identificar'
    | '/parceria'
    | '/ph'
    | '/sobre'
    | '/transparencia'
    | '/equipamentos/$slug'
    | '/estofados/$slug'
    | '/ferramentas/diluicao'
    | '/ferramentas/precificacao'
    | '/fichas/$slug'
    | '/manchas/$slug'
    | '/onde-comprar/$slug'
    | '/onde-comprar/comparar'
    | '/produtos/$slug'
    | '/produtos/comparar'
    | '/tecidos/$slug'
    | '/equipamentos/'
    | '/estofados/'
    | '/ferramentas/'
    | '/fichas/'
    | '/manchas/'
    | '/onde-comprar/'
    | '/produtos/'
    | '/tecidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprender'
    | '/automotiva'
    | '/buscar'
    | '/checklist'
    | '/comecar'
    | '/comunidade'
    | '/cuidados'
    | '/favoritos'
    | '/fluxo'
    | '/glossario'
    | '/guia'
    | '/identificar'
    | '/parceria'
    | '/ph'
    | '/sobre'
    | '/transparencia'
    | '/equipamentos/$slug'
    | '/estofados/$slug'
    | '/ferramentas/diluicao'
    | '/ferramentas/precificacao'
    | '/fichas/$slug'
    | '/manchas/$slug'
    | '/onde-comprar/$slug'
    | '/onde-comprar/comparar'
    | '/produtos/$slug'
    | '/produtos/comparar'
    | '/tecidos/$slug'
    | '/equipamentos'
    | '/estofados'
    | '/ferramentas'
    | '/fichas'
    | '/manchas'
    | '/onde-comprar'
    | '/produtos'
    | '/tecidos'
  id:
    | '__root__'
    | '/'
    | '/aprender'
    | '/automotiva'
    | '/buscar'
    | '/checklist'
    | '/comecar'
    | '/comunidade'
    | '/cuidados'
    | '/favoritos'
    | '/fluxo'
    | '/glossario'
    | '/guia'
    | '/identificar'
    | '/parceria'
    | '/ph'
    | '/sobre'
    | '/transparencia'
    | '/equipamentos/$slug'
    | '/estofados/$slug'
    | '/ferramentas/diluicao'
    | '/ferramentas/precificacao'
    | '/fichas/$slug'
    | '/manchas/$slug'
    | '/onde-comprar/$slug'
    | '/onde-comprar/comparar'
    | '/produtos/$slug'
    | '/produtos/comparar'
    | '/tecidos/$slug'
    | '/equipamentos/'
    | '/estofados/'
    | '/ferramentas/'
    | '/fichas/'
    | '/manchas/'
    | '/onde-comprar/'
    | '/produtos/'
    | '/tecidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprenderRoute: typeof AprenderRoute
  AutomotivaRoute: typeof AutomotivaRoute
  BuscarRoute: typeof BuscarRoute
  ChecklistRoute: typeof ChecklistRoute
  ComecarRoute: typeof ComecarRoute
  ComunidadeRoute: typeof ComunidadeRoute
  CuidadosRoute: typeof CuidadosRoute
  FavoritosRoute: typeof FavoritosRoute
  FluxoRoute: typeof FluxoRoute
  GlossarioRoute: typeof GlossarioRoute
  GuiaRoute: typeof GuiaRoute
  IdentificarRoute: typeof IdentificarRoute
  ParceriaRoute: typeof ParceriaRoute
  PhRoute: typeof PhRoute
  SobreRoute: typeof SobreRoute
  TransparenciaRoute: typeof TransparenciaRoute
  EquipamentosSlugRoute: typeof EquipamentosSlugRoute
  EstofadosSlugRoute: typeof EstofadosSlugRoute
  FerramentasDiluicaoRoute: typeof FerramentasDiluicaoRoute
  FerramentasPrecificacaoRoute: typeof FerramentasPrecificacaoRoute
  FichasSlugRoute: typeof FichasSlugRoute
  ManchasSlugRoute: typeof ManchasSlugRoute
  OndeComprarSlugRoute: typeof OndeComprarSlugRoute
  OndeComprarCompararRoute: typeof OndeComprarCompararRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosCompararRoute: typeof ProdutosCompararRoute
  TecidosSlugRoute: typeof TecidosSlugRoute
  EquipamentosIndexRoute: typeof EquipamentosIndexRoute
  EstofadosIndexRoute: typeof EstofadosIndexRoute
  FerramentasIndexRoute: typeof FerramentasIndexRoute
  FichasIndexRoute: typeof FichasIndexRoute
  ManchasIndexRoute: typeof ManchasIndexRoute
  OndeComprarIndexRoute: typeof OndeComprarIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
  TecidosIndexRoute: typeof TecidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender': {
      id: '/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AprenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automotiva': {
      id: '/automotiva'
      path: '/automotiva'
      fullPath: '/automotiva'
      preLoaderRoute: typeof AutomotivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidados': {
      id: '/cuidados'
      path: '/cuidados'
      fullPath: '/cuidados'
      preLoaderRoute: typeof CuidadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo': {
      id: '/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof FluxoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identificar': {
      id: '/identificar'
      path: '/identificar'
      fullPath: '/identificar'
      preLoaderRoute: typeof IdentificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceria': {
      id: '/parceria'
      path: '/parceria'
      fullPath: '/parceria'
      preLoaderRoute: typeof ParceriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ph': {
      id: '/ph'
      path: '/ph'
      fullPath: '/ph'
      preLoaderRoute: typeof PhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/': {
      id: '/equipamentos/'
      path: '/equipamentos'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof EquipamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/$slug': {
      id: '/equipamentos/$slug'
      path: '/equipamentos/$slug'
      fullPath: '/equipamentos/$slug'
      preLoaderRoute: typeof EquipamentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estofados/': {
      id: '/estofados/'
      path: '/estofados'
      fullPath: '/estofados/'
      preLoaderRoute: typeof EstofadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estofados/$slug': {
      id: '/estofados/$slug'
      path: '/estofados/$slug'
      fullPath: '/estofados/$slug'
      preLoaderRoute: typeof EstofadosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/': {
      id: '/ferramentas/'
      path: '/ferramentas'
      fullPath: '/ferramentas/'
      preLoaderRoute: typeof FerramentasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/diluicao': {
      id: '/ferramentas/diluicao'
      path: '/ferramentas/diluicao'
      fullPath: '/ferramentas/diluicao'
      preLoaderRoute: typeof FerramentasDiluicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/precificacao': {
      id: '/ferramentas/precificacao'
      path: '/ferramentas/precificacao'
      fullPath: '/ferramentas/precificacao'
      preLoaderRoute: typeof FerramentasPrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas/': {
      id: '/fichas/'
      path: '/fichas'
      fullPath: '/fichas/'
      preLoaderRoute: typeof FichasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas/$slug': {
      id: '/fichas/$slug'
      path: '/fichas/$slug'
      fullPath: '/fichas/$slug'
      preLoaderRoute: typeof FichasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manchas/': {
      id: '/manchas/'
      path: '/manchas'
      fullPath: '/manchas/'
      preLoaderRoute: typeof ManchasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manchas/$slug': {
      id: '/manchas/$slug'
      path: '/manchas/$slug'
      fullPath: '/manchas/$slug'
      preLoaderRoute: typeof ManchasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comprar/': {
      id: '/onde-comprar/'
      path: '/onde-comprar'
      fullPath: '/onde-comprar/'
      preLoaderRoute: typeof OndeComprarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comprar/$slug': {
      id: '/onde-comprar/$slug'
      path: '/onde-comprar/$slug'
      fullPath: '/onde-comprar/$slug'
      preLoaderRoute: typeof OndeComprarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comprar/comparar': {
      id: '/onde-comprar/comparar'
      path: '/onde-comprar/comparar'
      fullPath: '/onde-comprar/comparar'
      preLoaderRoute: typeof OndeComprarCompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/comparar': {
      id: '/produtos/comparar'
      path: '/produtos/comparar'
      fullPath: '/produtos/comparar'
      preLoaderRoute: typeof ProdutosCompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecidos/': {
      id: '/tecidos/'
      path: '/tecidos'
      fullPath: '/tecidos/'
      preLoaderRoute: typeof TecidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecidos/$slug': {
      id: '/tecidos/$slug'
      path: '/tecidos/$slug'
      fullPath: '/tecidos/$slug'
      preLoaderRoute: typeof TecidosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprenderRoute: AprenderRoute,
  AutomotivaRoute: AutomotivaRoute,
  BuscarRoute: BuscarRoute,
  ChecklistRoute: ChecklistRoute,
  ComecarRoute: ComecarRoute,
  ComunidadeRoute: ComunidadeRoute,
  CuidadosRoute: CuidadosRoute,
  FavoritosRoute: FavoritosRoute,
  FluxoRoute: FluxoRoute,
  GlossarioRoute: GlossarioRoute,
  GuiaRoute: GuiaRoute,
  IdentificarRoute: IdentificarRoute,
  ParceriaRoute: ParceriaRoute,
  PhRoute: PhRoute,
  SobreRoute: SobreRoute,
  TransparenciaRoute: TransparenciaRoute,
  EquipamentosSlugRoute: EquipamentosSlugRoute,
  EstofadosSlugRoute: EstofadosSlugRoute,
  FerramentasDiluicaoRoute: FerramentasDiluicaoRoute,
  FerramentasPrecificacaoRoute: FerramentasPrecificacaoRoute,
  FichasSlugRoute: FichasSlugRoute,
  ManchasSlugRoute: ManchasSlugRoute,
  OndeComprarSlugRoute: OndeComprarSlugRoute,
  OndeComprarCompararRoute: OndeComprarCompararRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosCompararRoute: ProdutosCompararRoute,
  TecidosSlugRoute: TecidosSlugRoute,
  EquipamentosIndexRoute: EquipamentosIndexRoute,
  EstofadosIndexRoute: EstofadosIndexRoute,
  FerramentasIndexRoute: FerramentasIndexRoute,
  FichasIndexRoute: FichasIndexRoute,
  ManchasIndexRoute: ManchasIndexRoute,
  OndeComprarIndexRoute: OndeComprarIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
  TecidosIndexRoute: TecidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
